name: dentistry
description: An Aqueduct application with a database connection and data model.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.1.0"

dependencies:
  aqueduct: ^3.0.0
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  jaguar_jwt: ^2.1.6
  dartz: ^0.9.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  injectable_generator: ^0.4.1
  build_runner: ^1.10.0

dependency_overrides:
  postgres: ^2.1.1
